### ISSUE TITLE
'GenomicInteractions': 'ranges' must have the length of the object to construct (1) or length 1

### ISSUE THREAD

**Issue by jaavedm** [mervesa/HiCDCPlus#2] opened 2021-01-17 22:40 UTC
Hello @mervesa,

After working around the gi_list_write() error, I am facing a new issue with HiCDCPlus. The error I'm getting now is in the function add_hicpro_allvalidpairs_counts.

The error I'm getting is 
```
[1] "Chromosome chr1 intrachromosomal counts processed."
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'anchor1' in selecting a method for function 'GenomicInteractions': 'ranges' must have the length of the object to construct (1) or length
  1
```

The R traceback() function returns:

```
9: h(simpleError(msg, call))
8: .handleSimpleError(function (cond)
   .Internal(C_tryCatchHelper(addr, 1L, cond)), "'ranges' must have the length of the object to construct (1) or length\n  1",
       base::quote(stop_if_wrong_length(what, ans_len)))
7: stop(wmsg(what, " must have the length of the object ", "to construct (",
       ans_len, ") or length 1"))
6: stop_if_wrong_length(what, ans_len)
5: new_GRanges("GRanges", seqnames = seqnames, ranges = ranges,
       strand = strand, mcols = mcols, seqinfo = seqinfo)
4: GenomicRanges::GRanges(chrom, IRanges::IRanges(df$startI, df$startI +
       1))
3: GenomicInteractions::GenomicInteractions(GenomicRanges::GRanges(chrom,
       IRanges::IRanges(df$startI, df$startI + 1)), GenomicRanges::GRanges(chrom,
       IRanges::IRanges(df$startJ, df$startJ + 1)))
2: add_2D_features(gi_list[[chrom]], allvalidpairs_chr)
1: add_hicpro_allvalidpairs_counts(gi_list, allvalidpairs_path = hicfile_path)
```

My sessionInfo() returns:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /opt/apps/R-4.0.2/lib/R/lib/libRblas.so
LAPACK: /opt/apps/R-4.0.2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.3 BSgenome_1.58.0
 [3] rtracklayer_1.50.0                Biostrings_2.58.0
 [5] XVector_0.30.0                    DESeq2_1.30.0
 [7] SummarizedExperiment_1.20.0       Biobase_2.50.0
 [9] MatrixGenerics_1.2.0              matrixStats_0.57.0
[11] GenomicRanges_1.42.0              GenomeInfoDb_1.26.2
[13] IRanges_2.24.1                    S4Vectors_0.28.1
[15] BiocGenerics_0.36.0               HiCDCPlus_0.99.5
[17] data.table_1.13.6

loaded via a namespace (and not attached):
  [1] colorspace_2.0-0           ellipsis_0.3.1
  [3] biovizBase_1.38.0          htmlTable_2.1.0
  [5] base64enc_0.1-3            dichromat_2.0-0
  [7] rstudioapi_0.13            bit64_4.0.5
  [9] AnnotationDbi_1.52.0       xml2_1.3.2
 [11] splines_4.0.2              R.methodsS3_1.8.1
 [13] geneplotter_1.68.0         knitr_1.30
 [15] Formula_1.2-4              Rsamtools_2.6.0
 [17] annotate_1.68.0            cluster_2.1.0
 [19] dbplyr_2.0.0               png_0.1-7
 [21] R.oo_1.24.0                compiler_4.0.2
 [23] httr_1.4.2                 backports_1.2.1
 [25] assertthat_0.2.1           Matrix_1.3-0
 [27] lazyeval_0.2.2             htmltools_0.5.1
 [29] prettyunits_1.1.1          tools_4.0.2
 [31] igraph_1.2.6               gtable_0.3.0
 [33] glue_1.4.2                 GenomeInfoDbData_1.2.4
 [35] dplyr_1.0.2                rappdirs_0.3.1
 [37] Rcpp_1.0.5                 vctrs_0.3.6
 [39] xfun_0.20                  stringr_1.4.0
 [41] lifecycle_0.2.0            ensembldb_2.14.0
 [43] XML_3.99-0.5               InteractionSet_1.18.0
 [45] zlibbioc_1.36.0            scales_1.1.1
 [47] VariantAnnotation_1.36.0   GenomicInteractions_1.24.0
 [49] hms_1.0.0                  ProtGenerics_1.22.0
 [51] AnnotationFilter_1.14.0    RColorBrewer_1.1-2
 [53] curl_4.3                   memoise_1.1.0
 [55] gridExtra_2.3              ggplot2_3.3.3
 [57] biomaRt_2.46.0             rpart_4.1-15
 [59] latticeExtra_0.6-29        stringi_1.5.3
 [61] RSQLite_2.2.2              genefilter_1.72.0
 [63] checkmate_2.0.0            GenomicFeatures_1.42.1
 [65] BiocParallel_1.24.1        rlang_0.4.10
 [67] pkgconfig_2.0.3            bitops_1.0-6
 [69] lattice_0.20-41            purrr_0.3.4
 [71] GenomicAlignments_1.26.0   htmlwidgets_1.5.3
 [73] bit_4.0.4                  tidyselect_1.1.0
 [75] magrittr_2.0.1             R6_2.5.0
 [77] generics_0.1.0             Hmisc_4.4-2
 [79] DelayedArray_0.16.0        DBI_1.1.0
 [81] pillar_1.4.7               foreign_0.8-81
 [83] survival_3.2-7             RCurl_1.98-1.2
 [85] nnet_7.3-14                tibble_3.0.4
 [87] crayon_1.3.4               BiocFileCache_1.14.0
 [89] jpeg_0.1-8.1               progress_1.2.2
 [91] locfit_1.5-9.4             grid_4.0.2
 [93] blob_1.2.1                 digest_0.6.27
 [95] xtable_1.8-4               tidyr_1.1.2
 [97] R.utils_2.10.1             openssl_1.4.3
 [99] munsell_0.5.0              Gviz_1.34.0
[101] askpass_1.1
```

**Comment by jaavedm** [comment] 2021-01-17 22:44
Here is some source code that will reproduce the error.

This is how I construct my features object:

```
construct_features(output_path=paste0(outdir,"/hg38_25kb_GATC"),
                   gen="Hsapiens",gen_ver="hg38",
                   sig="GATC",bin_type="Bins-uniform",
                   binsize=25000,
                   chrs=paste0("chr", append(seq(1, 22), "X")))
```

Here is the code I used to add the valid pairs from HiCPro. 

```
hicfile_path <- "H9_H3K27ac_rep1.allValidPairs"
cat(sprintf("\n%d of %d: Starting to process file %s\n\n", i, length(hicfile_paths), hicfile_path));
output_path<-paste0(outdir,'/', gsub("^(.*[\\/])", "",gsub('.allValidPairs','.txt.gz',hicfile_path)))

#generate gi_list instance
gi_list<-generate_bintolen_gi_list(bintolen_path=paste0(outdir,"/hg38_25kb_GATC_bintolen.txt.gz"), gen="Hsapiens",gen_ver="hg38");
gi_list<-add_hicpro_allvalidpairs_counts(gi_list, allvalidpairs_path = hicfile_path)   # <--- This will fail
```


I sent you the file **H9_H3K27ac_rep1.allValidPairs** in a previous private email message.

**Comment by mervesa** [comment] 2021-01-20 14:16
Hi @jaavedm , Thank you very much for testing my code, identifying a bug and helping me replicate it. Turns out that the .allvalidpairs file does not have any reads involving chr10 and chr20 (you can check columns 2 and 5), but the gi_list object has it, hence the code fails at chr10 that comes after chr1 (in string sorted order). Your code above should work fine if you replace `chrs=paste0("chr", append(seq(1, 22), "X"))` with `chrs=paste0("chr", c(seq(1, 9), seq(11,19), seq(21,22), "X"))`

I need to raise a warning when that happens and remove these chromosomes from gi_list.

**Comment by jaavedm** [comment] 2021-01-21 00:33
Thank you @mervesa.

This sounds like a good work around. I will compile all unique chroms in the valid pairs file. Then I will call add_hicpro_allvalidpairs_count method with the "chr" parameter of this method to only add the chroms for which there is data.  

But I have to say I like your propose fix of dealing with missing chroms automagically instead of erroring.

**Comment by mervesa** [comment] 2021-01-21 03:23
Thanks again for confirming that expected behavior is restored with the workaround. Closing the issue.

**Closed as completed by mervesa** 2021-01-21 03:23 UTC
